import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer/Footer'
import classNames from 'classnames'
import { Header } from '@/components/Header/Header'

const font = Nunito({
  subsets: ['latin'],
  style: ['normal'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={classNames(font.className, 'bg-white')}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
